name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 主分支名称

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build and deploy
      run: |
        cd excalidraw-app   # 进入目标子目录
        mv * ../              # 移动文件到根目录
        cd ..       
